# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jacobi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cjacobi.proto\":\n\x07Request\x12\t\n\x01\x41\x18\x01 \x01(\x0c\x12\t\n\x01\x42\x18\x02 \x01(\x0c\x12\t\n\x01x\x18\x03 \x01(\x0c\x12\x0e\n\x06offset\x18\x04 \x01(\x05\"\x13\n\x06Result\x12\t\n\x01x\x18\x01 \x01(\x0c\x32)\n\nJacobiCalc\x12\x1b\n\x04\x43\x61lc\x12\x08.Request\x1a\x07.Result\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'jacobi_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'jacobi_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_JACOBICALC = DESCRIPTOR.services_by_name['JacobiCalc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=16
  _REQUEST._serialized_end=74
  _RESULT._serialized_start=76
  _RESULT._serialized_end=95
  _JACOBICALC._serialized_start=97
  _JACOBICALC._serialized_end=138
# @@protoc_insertion_point(module_scope)
